version: "3"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: .env
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
  db:
    image: postgres
    env_file: .env
    ports:
      - "5432:5432"
